<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EMF.Common\EMF.Common.csproj" />
    <ProjectReference Include="..\EMF.Inventory\EMF.Inventory.csproj" />
    <ProjectReference Include="..\EMF.Discovery\EMF.Discovery.csproj" />
    <ProjectReference Include="..\EMF.Orchestration\EMF.Orchestration.csproj" />
    <ProjectReference Include="..\EMF.Integrity\EMF.Integrity.csproj" />
    <ProjectReference Include="..\EMF.Persistence\EMF.Persistence.csproj" />
    <ProjectReference Include="..\EMF.Security.Azure\EMF.Security.Azure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
