using System.Text;
using System.Text.RegularExpressions;

namespace EMF.Extensions.VeteransClaims.Orchestration;

/// <summary>
/// An ephemeral, source-aware view of evidence text. Never writes artifacts or
/// changes printable source images, selection, provenance, or clinical meaning.
/// </summary>
internal sealed class VeteransReviewerEvidencePresentation
{
    private const string Date = @"(?:[A-Za-z]+\s+\d{1,2},\s+\d{4}|\d{1,2}/\d{1,2}/\d{4}|\d{4}-\d{2}-\d{2})";
    private const string Identity = @"(?<identity>(?<name>[\p{L}'’-]+,\s*[\p{L} .’'-]{1,100}?)\s+(?:Date of birth|DOB):\s*" + Date + ")";
    private const string Generation = @"Report generated by My HealtheVet on VA\.gov on\s+" + Date;
    private const string Page = @"Page\s+\d+\s+of\s+\d+";
    private static readonly Regex CompleteHeader = Pattern(Identity + @"\s+" + Generation + @"\s+" + Page + @"\b");
    private static readonly Regex Footer = Pattern(Generation + @"\s+" + Page + @"\b");
    private static readonly Regex PageLine = Pattern(@"^\s*" + Page + @"\s*$");
    private static readonly Regex GenerationFragment = Pattern(Generation + @"\b");
    private static readonly Regex StandaloneGenerationLine = new(
        @"(?m)^[ \t]*" + Generation + @"[ \t]*\r?$",
        RegexOptions.CultureInvariant, TimeSpan.FromSeconds(1));
    // Never infer the extent of a multiline name from capitalization. Exact
    // tokens come from a complete producer header or the known veteran name.
    private const string HeaderNameToken = @"(?-i:\p{Lu}[\p{L}’'-]*)";
    private static readonly Regex NameToken = Pattern(@"\A" + HeaderNameToken + @"\z");
    private readonly Regex? _scrambledIdentity;
    private readonly Regex? _footerWithIdentity;
    private static readonly Regex DobFragment = Pattern(
        @"\b(?:Date of birth|DOB):[ \t]*" + Date + @"\b");
    private readonly HashSet<string> _verifiedIdentities = new(StringComparer.Ordinal);

    public bool IsBlueButton { get; }

    public List<VeteransReviewerTextCorrection> Corrections { get; } = [];


    private VeteransReviewerEvidencePresentation(
        bool isBlueButton, IEnumerable<string> texts, string? veteranDisplayName)
    {
        IsBlueButton = isBlueButton;
        if (!isBlueButton)
            return;

        var verifiedNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var text in texts)
        foreach (Match header in CompleteHeader.Matches(text))
        {
            _verifiedIdentities.Add(CollapseWhitespace(header.Groups["identity"].Value));
            verifiedNames.Add(CollapseWhitespace(header.Groups["name"].Value));
        }

        // A complete source header is stronger evidence than a display label,
        // which may omit middle names. Do not add shorter display-name variants
        // when the source already establishes its full header identity.
        if (verifiedNames.Count == 0 && !string.IsNullOrWhiteSpace(veteranDisplayName))
        {
            var displayName = CollapseWhitespace(veteranDisplayName);
            var tokens = displayName.Split(' ');
            if (displayName.Contains(','))
                verifiedNames.Add(displayName);
            else if (tokens.Length >= 2)
                verifiedNames.Add(tokens[^1] + ", " + string.Join(" ", tokens[..^1]));
        }

        var namePatterns = verifiedNames
            .Select(BuildVerifiedNamePattern)
            .OfType<string>()
            .OrderByDescending(pattern => pattern.Length)
            .ToArray();
        if (namePatterns.Length > 0)
        {
            var pageAndIdentity = Page + @"\b[ \t\r\n]+(?:" +
                string.Join("|", namePatterns) +
                @")[ \t]*[""“”'‘’.,;]*[ \t]*(?=\r?$)";
            _scrambledIdentity = Pattern(
                @"(?m)\b" + pageAndIdentity);
            _footerWithIdentity = Pattern(
                @"(?m)" + Generation + @"\s+" + pageAndIdentity);
        }
    }

    public static VeteransReviewerEvidencePresentation Create(
        VeteransReviewerArtifactContent content,
        IEnumerable<string> printableText,
        string? veteranDisplayName = null)
    {
        // A mention in a letter or a scientific paper is not source provenance.
        var source = content.SourceName ?? content.Artifact.Name;
        var blueButton = Regex.IsMatch(source,
            @"\b(?:VA[ -]+)?Blue[ -]Button\b",
            RegexOptions.IgnoreCase | RegexOptions.CultureInvariant,
            TimeSpan.FromSeconds(1));
        return new(blueButton, printableText.Prepend(content.Text), veteranDisplayName);
    }

    public string Normalize(string text)
    {
        if (!IsBlueButton)
            return text;

        // Only a complete producer signature permits inline removal. Standalone
        // pagination is source-specific; narrative page references are retained.
        var cleaned = CompleteHeader.Replace(text, " ");
        cleaned = RemoveScrambledProducerFragments(cleaned);
        // Some extracted footers place the next exact producer identity after
        // the page counter. Remove it with its signature, never by name alone.
        if (_footerWithIdentity is not null)
            cleaned = _footerWithIdentity.Replace(cleaned, " ");
        cleaned = Footer.Replace(cleaned, " ");
        // A standalone generation line can still anchor a scrambled cluster.
        // Consume that signature before removing any remaining isolated lines.
        cleaned = StandaloneGenerationLine.Replace(cleaned, string.Empty);
        foreach (var identity in _verifiedIdentities)
        {
            // PDF extraction may split the same verified name/DOB across lines.
            var identityPattern = @"(?m)^[ \t]*" +
                string.Join(@"\s+", identity.Split(' ').Select(Regex.Escape)) + @"[ \t]*\r?$";
            cleaned = Pattern(identityPattern).Replace(cleaned, string.Empty);
        }
        var lines = cleaned.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Replace('\r', '\n').Split('\n');
        for (var index = 0; index < lines.Length; index++)
        {
            var line = lines[index];
            if (PageLine.IsMatch(line))
                lines[index] = string.Empty;
        }

        // Preserve row order, spacing, dates, doses and status values. In
        // particular, ACTIVE is clinical data, not a safe deletion keyword.
        return string.Join("\n", lines);
    }

    private string RemoveScrambledProducerFragments(string text)
    {
        if (_scrambledIdentity is null)
            return text;

        const int maximumClusterLength = 4096;
        var removals = new List<(int Index, int Length)>();
        var precedingIdentityEnd = 0;
        foreach (Match identity in _scrambledIdentity.Matches(text))
        {
            var start = Math.Max(precedingIdentityEnd, identity.Index - maximumClusterLength);
            var preceding = text[start..identity.Index];
            var generations = GenerationFragment.Matches(preceding);
            if (generations.Count != 1)
            {
                precedingIdentityEnd = identity.Index + identity.Length;
                continue;
            }
            var generation = generations[0];
            var afterGeneration = generation.Index + generation.Length;
            var births = DobFragment.Matches(preceding[afterGeneration..]);
            // Multiple dates or producer markers are ambiguous. Leave that
            // cluster intact instead of globally deleting DOBs or names.
            if (births.Count == 1)
            {
                removals.Add((start + generation.Index, generation.Length));
                removals.Add((start + afterGeneration + births[0].Index, births[0].Length));
                removals.Add((identity.Index, identity.Length));
            }
            precedingIdentityEnd = identity.Index + identity.Length;
        }

        var cleaned = new StringBuilder(text);
        foreach (var removal in removals.OrderByDescending(removal => removal.Index))
            cleaned.Remove(removal.Index, removal.Length);
        return cleaned.ToString();
    }

    private static string? BuildVerifiedNamePattern(string name)
    {
        var parts = name.Split(',');
        if (parts.Length != 2)
            return null;
        var surname = parts[0].Trim();
        var givenNames = parts[1].Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (!NameToken.IsMatch(surname) || givenNames.Length is < 1 or > 4 ||
            givenNames.Any(token => !NameToken.IsMatch(token)))
            return null;

        // Preserve the uppercase-token constraint while allowing casing
        // differences between a display label and the producer's header.
        static string Token(string token) => @"(?-i:(?=\p{Lu}))" + Regex.Escape(token);
        return Token(surname) + @",[ \t\r\n]*" +
            string.Join(@"[ \t\r\n]+", givenNames.Select(Token));
    }

    private static string CollapseWhitespace(string text) =>
        Regex.Replace(text, @"\s+", " ", RegexOptions.CultureInvariant,
            TimeSpan.FromSeconds(1)).Trim();

    private static Regex Pattern(string pattern) => new(pattern,
        RegexOptions.IgnoreCase | RegexOptions.CultureInvariant,
        TimeSpan.FromSeconds(1));
}
