using System.Text.RegularExpressions;
using EMF.Core.Models;

namespace EMF.Extensions.VeteransClaims.Orchestration;

// A hanging narrative has long lines at a common indent and short overflow
// fragments at the margin on separate baselines. Those fragments are not cells.
// This detector uses geometry and typography, never record titles or page IDs.
internal static class VeteransReviewerNativeProse
{
    internal sealed record Line(string Text, double X, double Baseline, double Size,
        string Font, bool Columns, int Page)
    {
        public string FixedText { get; init; } = Text;
        public bool Mono => Font.Contains("Mono", StringComparison.OrdinalIgnoreCase) ||
            Font.Contains("Courier", StringComparison.OrdinalIgnoreCase);
        public bool Field => Regex.IsMatch(Text, @"^[A-Za-z][A-Za-z /()-]{0,39}:");
        public bool Fragment => Mono && !Columns && !Field && Text.Any(char.IsLower) &&
            Text.Split(' ', StringSplitOptions.RemoveEmptyEntries).Length <= 2 &&
            !Regex.IsMatch(Text, @"^(?:\d|[-*/])") && !Text.EndsWith(':');
    }

    internal static IReadOnlyList<Line> Lines(PrintableArtifactPage page)
    {
        var result = new List<Line>();
        foreach (var row in page.TextGeometry!.Glyphs.Where(g => !string.IsNullOrWhiteSpace(g.Text))
                     .GroupBy(g => Math.Round(g.Baseline, 1)).OrderBy(g => g.Key))
        {
            var glyphs = row.OrderBy(g => g.X).ToArray();
            var text = "";
            var fixedText = "";
            var columns = false;
            PrintableArtifactGlyph? previous = null;
            foreach (var glyph in glyphs)
            {
                var gap = previous is null ? 0 : glyph.X - previous.EndX;
                if (gap > glyph.FontSize * .15)
                {
                    text += " ";
                    fixedText += new string(' ', Math.Max(1, (int)Math.Round(gap / (glyph.FontSize * .6))));
                }
                columns |= gap > glyph.FontSize * 1.6;
                text += glyph.Text;
                fixedText += glyph.Text;
                previous = glyph;
            }
            var first = glyphs[0];
            result.Add(new(text, first.X, first.Baseline, first.FontSize, first.Font, columns, page.PageNumber) { FixedText = fixedText });
        }
        return result;
    }

    public static IReadOnlyList<string>? Reconstruct(IReadOnlyList<PrintableArtifactPage> pages)
    {
        if (pages.Count == 0 || pages.Any(p => p.ContentType != "image/png" ||
            p.SuggestedClockwiseRotation != 0 ||
            p.TextGeometry is not { ContainsGraphics: false, Width: > 0, Height: > 0 })) return null;
        var seenPatientHeaders = new HashSet<string>(StringComparer.Ordinal);
        var rows = pages.SelectMany(page => Lines(page).Where(row =>
            // Only known repeating Blue Button furniture is excluded. All
            // clinical words, including short margin fragments, remain ordered.
            !(row.Baseline < page.TextGeometry!.Height * .05 && row.Text.Contains("Date of birth:") &&
              !seenPatientHeaders.Add(row.Text)) &&
            !(row.Baseline > page.TextGeometry!.Height * .95 &&
              Regex.IsMatch(row.Text, @"^Report generated by My HealtheVet on VA\.gov on .+Page \d+ of \d+$"))))
            .ToArray();
        var candidates = new List<double>();
        for (var i = 1; i + 1 < rows.Length; i++)
        {
            var row = rows[i]; var before = rows[i - 1]; var after = rows[i + 1];
            if (row.Fragment && before.Mono && after.Mono && !before.Columns && !after.Columns &&
                Math.Abs(before.X - after.X) < 1 && before.X - row.X > row.Size * 3 &&
                before.Font == row.Font && after.Font == row.Font &&
                Math.Abs(before.Size - row.Size) < .1 && Math.Abs(after.Size - row.Size) < .1 &&
                before.Text.Any(char.IsLower) && after.Text.Any(char.IsLower)) candidates.Add(before.X);
        }
        var anchor = candidates.GroupBy(x => Math.Round(x)).OrderByDescending(g => g.Count()).FirstOrDefault();
        if (anchor is null || anchor.Count() < 2) return null;
        var indent = anchor.Average();
        var paragraphs = new List<string>();
        var current = "";
        Line? previous = null;
        var prose = false;
        var signature = false;
        void Flush() { if (current.Length > 0) paragraphs.Add(current); current = ""; }
        foreach (var row in rows)
        {
            var atIndent = row.Mono && Math.Abs(row.X - indent) < 1 && !row.Columns;
            var marginFragment = row.Fragment && row.X < indent;
            // Labels and aligned multi-cell rows remain explicit boundaries.
            // Their sentence-like values can continue on subsequent baselines.
            var proseField = row.Mono && row.Field && row.Text.Count(char.IsLower) > 18 &&
                row.Text.Split(' ').Length >= 5;
            var narrative = row.Mono && !row.Columns && !row.Field &&
                row.Text.Count(char.IsLower) > 15 && !Regex.IsMatch(row.Text, @"^(?:/es/|\d|[A-Z]\d)");
            var newItem = Regex.IsMatch(row.Text, @"^(?:-\s|\d+[.)]\s|\d{4,},|[A-Z]\d+[.,])");
            var adjacent = previous is not null && (row.Page == previous.Page + 1 ||
                (row.Page == previous.Page && row.Baseline - previous.Baseline < Math.Max(row.Size, previous.Size) * 1.8));
            // A signature is a structured entry, not several independent
            // paragraphs when names or credentials wrap at the source margin.
            var signatureContinuation = signature && adjacent && row.Mono &&
                !row.Columns && !row.Field && row.Text.Split(' ', StringSplitOptions.RemoveEmptyEntries).Length <= 4 &&
                !Regex.IsMatch(row.Text, @"^(?:\d|/es/|[-*])");
            var joins = signatureContinuation || (prose && adjacent && (!row.Field || atIndent || char.IsLower(row.Text[0])) && !row.Columns && !newItem &&
                (atIndent || marginFragment || (row.Field && char.IsLower(row.Text[0]) && previous is not null && Math.Abs(row.X - previous.X) < 1) || (narrative && previous is not null && (previous.Fragment || Math.Abs(row.X - previous.X) < 1))));
            if (!joins) Flush();
            if (current.Length > 0) current += " ";
            current += joins || atIndent || narrative || proseField || !row.Mono ? row.Text : row.FixedText;
            signature = row.Text.Contains("/es/", StringComparison.Ordinal) || signatureContinuation;
            prose = !signature && (joins || atIndent || narrative || proseField);
            // Sentence completion is a natural paragraph boundary. A short
            // following fragment can start the next sentence without isolation.
            if (Regex.IsMatch(row.Text, "[.!?][\\\"')]*$") && !marginFragment)
            { Flush(); prose = false; }
            if (marginFragment && current == row.Text) prose = true;
            previous = row;
        }
        Flush();
        return paragraphs;
    }
}
