using System.Security.Cryptography;
using System.Text;
using EMF.Core.Models;
using EMF.Core.Models.Integrity;
using EMF.Extensions.VeteransClaims.Models.Medications;
using EMF.Extensions.VeteransClaims.Orchestration;
using EMF.Extensions.VeteransClaims.Services;

namespace EMF.Tests;

public sealed class VeteransMedicationSourceEvidenceServiceTests
{
    [Theory]
    [InlineData(true, "RX-EXAMPLE", "", true)]
    [InlineData(true, "RX-EXAMPLE", "Non-VA clinic", false)]
    [InlineData(true, "RX-OTHER", "", false)]
    [InlineData(false, "RX-EXAMPLE", "", false)]
    public void MissingFacilityUsesVerifiedPrescriptionRecordNotFilenameOrNumberFormat(
        bool vaReport, string prescription, string facility, bool expected)
    {
        var text = SourceText(vaReport, prescription, facility);
        var bytes = Encoding.UTF8.GetBytes("%PDF-" + text);
        var (ledger, entry) = Records();
        var artifact = Artifact(bytes);

        Assert.True(VeteransMedicationSourceEvidenceService.VerifySourceArtifact(
            artifact, bytes, ledger));

        var evidence = VeteransMedicationSourceEvidenceService.ReadVerifiedRecord(
            artifact, ledger, entry, text);

        Assert.Equal(expected, MedicationLedgerSource.IsVaPrescription(entry, evidence));
        Assert.Null(entry.Facility);
        if (expected)
        {
            Assert.NotNull(evidence);
            Assert.Contains("source pages 1–1", evidence.SourceLocator);
        }
    }

    [Fact]
    public void SourceFingerprintMismatchIsNotAccepted()
    {
        var bytes = Encoding.UTF8.GetBytes("%PDF-" + SourceText(true, "RX-EXAMPLE", ""));
        var otherBytes = Encoding.UTF8.GetBytes("%PDF-" + SourceText(false, "RX-EXAMPLE", ""));
        var (ledger, _) = Records();

        Assert.Throws<InvalidDataException>(() =>
            VeteransMedicationSourceEvidenceService.VerifySourceArtifact(
                Artifact(otherBytes), bytes, ledger));
    }

    [Fact]
    public void MissingSourceFingerprintRemainsUnresolved()
    {
        var bytes = Encoding.UTF8.GetBytes("%PDF-" + SourceText(true, "RX-EXAMPLE", ""));
        var (ledger, _) = Records();

        Assert.False(VeteransMedicationSourceEvidenceService.VerifySourceArtifact(
            new Artifact { Id = new("source"), Name = "VA-Blue-Button-report.pdf", ArtifactType = "pdf" },
            bytes,
            ledger));
    }

    private static Artifact Artifact(byte[] bytes) => new()
    {
        Id = new("source"), Name = "VA-Blue-Button-report.pdf", ArtifactType = "pdf",
        Fingerprint = new ContentFingerprint { Algorithm = "SHA256", Value = Convert.ToHexString(SHA256.HashData(bytes)) }
    };

    private static (MedicationLedger, MedicationLedgerEntry) Records() => (new()
    {
        Id = new("ledger"), VeteranId = new("veteran"), SourceArtifactId = new("source"),
        ReportDate = new(2026, 9, 9), SourceStartPage = 1, SourceEndPage = 1, ParsedEntryCount = 1, IsComplete = true
    }, new()
    {
        Id = new("entry"), MedicationLedgerId = new("ledger"), MedicationName = "Example medicine", Status = "active",
        EntryOrdinal = 1, SourceStartPage = 1, SourceEndPage = 1, PrescriptionNumber = "RX-EXAMPLE"
    });

    private static string SourceText(bool vaReport, string prescription, string facility) =>
        string.Join(Environment.NewLine,
            "Example medicine",
            "About your prescription",
            "Status: active",
            "Prescription number: " + prescription,
            "Prescribed by: Example Provider",
            "Facility: " + facility,
            "Instructions: Original wording.",
            vaReport
                ? "Report generated by My HealtheVet on VA.gov on September 9, 2026"
                : "Community report");
}
