using EMF.Core.Models;
using EMF.Extensions.VeteransClaims.Orchestration;

namespace EMF.Tests;

public sealed class VeteransBlueButtonMedicationLedgerParserTests
{
    [Fact]
    public void Parse_ReadsAuthoritativeMedicationLedger()
    {
        var result =
            new VeteransBlueButtonMedicationLedgerParser()
                .Parse(
                [
                    Page(
                        3910,
                        """
                        Records in this report
                        Care summaries and notes
                        Medications
                        My HealtheVet account summary

                        Medications
                        This is a list of prescriptions and other medications in your VA medical records.
                        Showing 2 medications, alphabetically by name

                        buPROPion (buPROPion XL 300 mg/24 hour tablet)

                             About your prescription
                             Last filled on: July 2, 2026
                             Status: active
                             Refills left: 2
                             Request refills by this prescription expiration date: February 28, 2027
                             Prescription number: 3211-50183021
                             Prescribed on: August 21, 2026
                             Prescribed by: CLARK, DAVID G, MD
                             Facility: Richard L. Roudebush Veterans' Administration Medical Center
                             Pharmacy phone number: Unknown

                             About this medication or supply
                             Instructions: TAKE ONE TABLET ORALLY EVERY MORNING FOR MOOD
                             Reason for use: FOR MOOD
                             Quantity: 90

                        Report generated by My HealtheVet on VA.gov on September 9, 2026 Page 3910 of 4024
                        """),
                    Page(
                        3911,
                        """
                        Gould, Michael Allen Date of birth: April 12, 1956

                        isosorbide mononitrate (isosorbide mononitrate ER 30 mg/24 hour
                        tablet)

                             About your prescription
                             Last filled on: Not filled yet
                             Status: refillinprocess
                             Refills left: 3
                             Request refills by this prescription expiration date: August 17, 2027
                             Prescription number: 3211-50014120
                             Prescribed on: August 21, 2026
                             Prescribed by: POWELL, LYNN M, NP
                             Facility: Richard L. Roudebush Veterans' Administration Medical Center

                             About this medication or supply
                             Instructions: See Instructions. TAKE ONE TABLET ORALLY EVERY DAY WITH BREAKFAST FOR PREVENTING
                             CHEST PAIN. Refills: 3.
                             Reason for use: FOR PREVENTING CHEST PAIN
                             Quantity: 90

                        Report generated by My HealtheVet on VA.gov on September 9, 2026 Page 3911 of 4024
                        My HealtheVet account summary
                        """)
                ]);

        Assert.Equal(new DateOnly(2026, 9, 9), result.ReportDate);
        Assert.Equal(3910, result.SourceStartPage);
        Assert.Equal(3911, result.SourceEndPage);
        Assert.Equal(2, result.ReportedEntryCount);
        Assert.Equal(2, result.ParsedEntryCount);
        Assert.True(result.IsComplete);

        var bupropion = result.Entries[0];
        Assert.Equal(1, bupropion.EntryOrdinal);
        Assert.Equal(
            "buPROPion (buPROPion XL 300 mg/24 hour tablet)",
            bupropion.MedicationName);
        Assert.Equal("300 mg/24 hour", bupropion.Strength);
        Assert.Equal("active", bupropion.Status);
        Assert.Equal("3211-50183021", bupropion.PrescriptionNumber);
        Assert.Equal(new DateOnly(2026, 8, 21), bupropion.PrescribedDate);
        Assert.Equal(new DateOnly(2026, 7, 2), bupropion.LastFilledDate);
        Assert.Equal("July 2, 2026", bupropion.LastFilledOnText);
        Assert.Equal(new DateOnly(2027, 2, 28), bupropion.ExpirationDate);
        Assert.Equal(2, bupropion.RefillsLeft);
        Assert.Equal("FOR MOOD", bupropion.Indication);
        Assert.Equal("CLARK, DAVID G, MD", bupropion.Prescriber);
        Assert.Equal("90", bupropion.Quantity);

        var isosorbide = result.Entries[1];
        Assert.Equal(3911, isosorbide.SourceStartPage);
        Assert.Equal(3911, isosorbide.SourceEndPage);
        Assert.Equal(
            "isosorbide mononitrate (isosorbide mononitrate ER 30 mg/24 hour tablet)",
            isosorbide.MedicationName);
        Assert.Equal("30 mg/24 hour", isosorbide.Strength);
        Assert.Equal("refillinprocess", isosorbide.Status);
        Assert.Null(isosorbide.LastFilledDate);
        Assert.Equal("Not filled yet", isosorbide.LastFilledOnText);
        Assert.Contains(
            "PREVENTING CHEST PAIN. Refills: 3.",
            isosorbide.Directions);
    }

    [Fact]
    public void Parse_PreservesTransferredLegacyPrescriptionAcrossPageBreak()
    {
        var result =
            new VeteransBlueButtonMedicationLedgerParser()
                .Parse(
                [
                    Page(
                        4021,
                        """
                        Medications
                        This is a list of prescriptions and other medications in your VA medical records.
                        Showing 1 medications, alphabetically by name

                        TRAZODONE HCL 100MG TAB

                             About your prescription
                        Report generated by My HealtheVet on VA.gov on September 9, 2026 Page 4021 of 4024
                        """),
                    Page(
                        4022,
                        """
                        Gould, Michael Allen Date of birth: April 12, 1956
                             Last filled on: Not filled yet
                             Status: transferred
                             Refills left: 1
                             Request refills by this prescription expiration date: August 5, 2027
                             Prescription number: 50062896E
                             Prescribed on: August 4, 2026
                             Prescribed by: GOERGEN, JOSHUA

                             About this medication or supply
                             Instructions: TAKE THREE TABLETS ORALLY AT BEDTIME FOR INSOMNIA
                             Reason for use: FOR INSOMNIA
                             Quantity: 270

                        Report generated by My HealtheVet on VA.gov on September 9, 2026 Page 4022 of 4024
                        My HealtheVet account summary
                        """)
                ]);

        var entry = Assert.Single(result.Entries);
        Assert.Equal("TRAZODONE HCL 100MG TAB", entry.MedicationName);
        Assert.Equal("100MG", entry.Strength);
        Assert.Equal("transferred", entry.Status);
        Assert.Equal(4021, entry.SourceStartPage);
        Assert.Equal(4022, entry.SourceEndPage);
        Assert.True(result.IsComplete);
    }

    [Fact]
    public void Parse_SeparatesAdjacentEntriesWithoutBlankLines()
    {
        var result =
            new VeteransBlueButtonMedicationLedgerParser()
                .Parse(
                [
                    Page(
                        3900,
                        """
                        Medications
                        This is a list of prescriptions and other medications in your VA medical records.
                        Showing 2 medications, alphabetically by name
                        sertraline (sertraline 50 mg tablet)
                        About your prescription
                        Last filled on: August 5, 2026
                        Status: active
                        Prescription number: 3211-50301417
                        About this medication or supply
                        Instructions: TAKE ONE TABLET ORALLY EVERY MORNING FOR MOOD
                        Reason for use: FOR MOOD
                        Quantity: 90
                        traZODone (traZODone 100 mg tablet)
                        About your prescription
                        Last filled on: August 28, 2026
                        Status: active
                        Prescription number: 3211-50428072
                        About this medication or supply
                        Instructions: TAKE THREE TABLETS ORALLY AT BEDTIME FOR INSOMNIA
                        Reason for use: FOR INSOMNIA
                        Quantity: 270
                        Report generated by My HealtheVet on VA.gov on September 9, 2026 Page 3900 of 4024
                        My HealtheVet account summary
                        """)
                ]);

        Assert.Equal(2, result.ParsedEntryCount);
        Assert.True(result.IsComplete);

        Assert.Equal(
            "sertraline (sertraline 50 mg tablet)",
            result.Entries[0].MedicationName);
        Assert.Equal("90", result.Entries[0].Quantity);

        Assert.Equal(
            "traZODone (traZODone 100 mg tablet)",
            result.Entries[1].MedicationName);
        Assert.Equal("270", result.Entries[1].Quantity);
    }

    [Fact]
    public void Parse_MarksLedgerIncompleteWhenReportedCountDoesNotMatch()
    {
        var result =
            new VeteransBlueButtonMedicationLedgerParser()
                .Parse(
                [
                    Page(
                        3900,
                        """
                        Medications
                        This is a list of prescriptions and other medications in your VA medical records.
                        Showing 2 medications, alphabetically by name

                        FENOFIBRATE 145MG TAB

                             About your prescription
                             Last filled on: September 2, 2026
                             Status: active
                             Prescription number: 3211-50443431

                        Report generated by My HealtheVet on VA.gov on September 9, 2026 Page 3900 of 4024
                        My HealtheVet account summary
                        """)
                ]);

        Assert.Equal(2, result.ReportedEntryCount);
        Assert.Equal(1, result.ParsedEntryCount);
        Assert.False(result.IsComplete);
    }

    [Fact]
    public void Parse_RejectsMissingAuthoritativeMedicationSection()
    {
        var ex =
            Assert.Throws<InvalidDataException>(
                () =>
                    new VeteransBlueButtonMedicationLedgerParser()
                        .Parse(
                        [
                            Page(
                                1,
                                """
                                Care summaries and notes
                                Medications
                                ACTIVE outpatient medication text
                                Vaccines
                                """)
                        ]));

        Assert.Equal(
            "Blue Button medications section was not found.",
            ex.Message);
    }

    [Fact]
    public void Parse_RejectsNonPositivePageNumber()
    {
        Assert.Throws<InvalidDataException>(
            () =>
                new VeteransBlueButtonMedicationLedgerParser()
                    .Parse(
                    [
                        Page(
                            0,
                            "Medications")
                    ]));
    }

    private static ExtractedArtifactTextPage Page(
        int pageNumber,
        string text) =>
        new()
        {
            PageNumber = pageNumber,
            Text = text
        };
}
