using EMF.Core.Models;
using EMF.Extensions.VeteransClaims.Orchestration;
using SkiaSharp;

namespace EMF.Tests;

public sealed class VeteransReviewerNativeEvidencePageTests
{
    [Fact]
    public void NativeCleanup_RemovesOnlyIdentifiedFooterAndConservesEveryClinicalPixel()
    {
        using var fixture = new NativePage();
        fixture.Line("Patient name", 15, font: "SourceSansPro");
        fixture.Line("A: Clinical findings with symptoms x", 70);
        fixture.Line("1", 85);
        fixture.Line("month. The original text is retained.", 100);
        fixture.Line("GOALS:", 145);
        fixture.Line("1. Preserve this numbered clinical goal.", 160);
        fixture.Line("Reference to My HealtheVet on VA.gov", 230);
        fixture.Line("Clinical content near footer", 382, size: 3);
        var expected = Ink(fixture.Bitmap);
        fixture.Line("Report generated by My HealtheVet on VA.gov on September 9, 2026Page 440 of 4024",
            390, font: "SourceSansPro", size: 3);
        var page = fixture.Page();
        var original = page.Content.ToArray();
        var result = VeteransReviewerNativeEvidencePage.Prepare(page, true);
        Assert.Contains(result.Changes, c => c.StartsWith("Removed native Blue Button footer"));
        Assert.Contains(result.Changes, c => c.StartsWith("Joined native prose"));
        using var cleaned = SKBitmap.Decode(result.Content.Span);
        Assert.Equal(expected, Ink(cleaned));
        Assert.True(cleaned.Height < fixture.Bitmap.Height);
        Assert.Equal(original, page.Content.ToArray());
    }

    [Fact]
    public void NativeCleanup_RetainsObjectiveHeadingAndFindingsAsOneFixedRegion()
    {
        using var fixture = new NativePage();
        fixture.Line("O:", 30);
        fixture.Line("GAIT: I with L AFO", 60);
        fixture.Line("Lumbar AROM: WFL", 105);
        var result = VeteransReviewerNativeEvidencePage.Prepare(fixture.Page(), true);
        Assert.DoesNotContain(result.Changes, c => c.StartsWith("Attached original O:"));
        AssertStructuredGeometry(fixture.Page(), result);
        Assert.Contains(result.Regions, r => r.Kind == "Structured" && r.SourceLines.Contains("O:") &&
            r.SourceLines.Contains("GAIT: I with L AFO"));
        using var cleaned = SKBitmap.Decode(result.Content.Span);
        Assert.Equal(Ink(fixture.Bitmap), Ink(cleaned));
    }

    [Theory]
    [InlineData("1. Clinical findings with symptoms x", 15, 0)]
    [InlineData("Clinical findings with symptoms x", 30, 0)]
    [InlineData("Clinical findings with symptoms x", 15, 24)]
    public void NativeCleanup_DoesNotJoinListsFieldsColumnsParagraphBreaksOrIndentChanges(
        string first, int pitch, int indent)
    {
        using var fixture = new NativePage();
        fixture.Line(first, 40);
        fixture.Line("1", 40 + pitch, x: 20 + indent);
        fixture.Line("month. Original clinical wording remains.", 40 + 2 * pitch);
        var result = VeteransReviewerNativeEvidencePage.Prepare(fixture.Page(), true);
        Assert.DoesNotContain(result.Changes, c => c.StartsWith("Joined native prose"));
        using var cleaned = SKBitmap.Decode(result.Content.Span);
        Assert.Equal(Ink(fixture.Bitmap), Ink(cleaned));
    }

    [Theory]
    [InlineData(false, false, false)]
    [InlineData(true, true, false)]
    [InlineData(true, false, true)]
    public void NativeCleanup_RequiresBlueButtonProvenanceAndUnambiguousGeometry(
        bool blueButton, bool hasGraphics, bool missingGeometry)
    {
        using var fixture = new NativePage();
        fixture.Line("A: Clinical findings with symptoms x", 40);
        fixture.Line("1", 55);
        fixture.Line("month. Original clinical wording remains.", 70);
        var page = fixture.Page(hasGraphics, missingGeometry);
        var result = VeteransReviewerNativeEvidencePage.Prepare(page, blueButton);
        Assert.Empty(result.Changes);
        var crop = VeteransReviewerSourcePageCrop.Crop(page.Content);
        VeteransReviewerSourcePageCropTests.AssertPreserved(page.Content, crop with { Content = result.Content });
    }

    [Fact]
    public void NativeCleanup_RejectsReflowWhenNativeGeometryDoesNotCoverEverySourceMark()
    {
        using var fixture = new NativePage();
        fixture.Line("A: Clinical findings with symptoms x", 40);
        fixture.Line("1", 55);
        fixture.Line("month. Original clinical wording remains.", 70);
        fixture.Bitmap.SetPixel(590, 110, new SKColor(254, 254, 255));
        var result = VeteransReviewerNativeEvidencePage.Prepare(fixture.Page(), true);
        Assert.DoesNotContain(result.Changes, c => c.StartsWith("Joined native prose"));
        using var cleaned = SKBitmap.Decode(result.Content.Span);
        Assert.Equal(Ink(fixture.Bitmap), Ink(cleaned));
    }

    [Fact]
    public void Page21_LocalAttendingLabelDoesNotMakeNeighboringProseStructured()
    {
        using var fixture = new NativePage(1224, 1584);
        fixture.Line("Signed: 01/01/2026", 52, size: 12, x: 45);
        fixture.Line("01/01/2026 ADDENDUM                     STATUS: COMPLETED", 88, size: 12, x: 45);
        fixture.Line("Attending: I saw and examined the patient.  I discussed the findings with", 106, size: 12, x: 45);
        fixture.Line("Dr.", 124, size: 12, x: 45);
        fixture.Line("Example and reviewed the note.  I agree wiht the fingings, assessment and", 142, size: 12, x: 45);
        fixture.Line("plan", 160, size: 12, x: 45);
        fixture.Line("as documented.  The patient has been taking the prescribed treatment", 178, size: 12, x: 45);
        fixture.Line("and is", 196, size: 12, x: 45);
        fixture.Line("waiting for the next appointment.", 214, size: 12, x: 45);
        var page = fixture.Page();
        var result = VeteransReviewerNativeEvidencePage.Prepare(page, true);
        var prose = Assert.Single(result.Regions.Where(r => r.Kind == "Narrative"));
        Assert.StartsWith("Attending:", prose.RenderedLines[0]);
        Assert.DoesNotContain(prose.RenderedLines, l => l is "Dr." or "plan" or "and is");
        Assert.Equal(Words(prose.SourceLines), Words(prose.RenderedLines));
        Assert.Contains("wiht", Words(prose.RenderedLines));
        Assert.Contains("fingings,", Words(prose.RenderedLines));
        Assert.True(prose.RenderedLines.Count < prose.SourceLines.Count);
        AssertAllInk(page, result);
        AssertStructuredGeometry(page, result);
    }

    [Theory]
    [InlineData("  ")]
    [InlineData("    ")]
    public void RepeatedSpacesAloneDoNotEstablishColumns(string spaces)
    {
        using var fixture = new NativePage(1224, 1584);
        fixture.Line("Attending: The visit was completed." + spaces + "We discussed care with", 50, size: 12, x: 45);
        fixture.Line("Dr.", 68, size: 12, x: 45);
        fixture.Line("Example and confirmed the next steps.", 86, size: 12, x: 45);
        var page = fixture.Page();
        var result = VeteransReviewerNativeEvidencePage.Prepare(page, true);
        var prose = Assert.Single(result.Regions);
        Assert.Equal("Narrative", prose.Kind);
        Assert.DoesNotContain(prose.RenderedLines, l => l == "Dr.");
        Assert.Equal(Words(prose.SourceLines), Words(prose.RenderedLines));
        AssertAllInk(page, result);
    }

    [Theory]
    [InlineData("Attending:")]
    [InlineData("Clinician:")]
    public void LocalLabelOnItsOwnLineDoesNotClassifyFollowingProseAsStructured(string label)
    {
        using var fixture = new NativePage(1224, 1584);
        fixture.Line(label, 32, size: 12, x: 45);
        fixture.Line("The patient described improvement after working with", 50, size: 12, x: 45);
        fixture.Line("Dr.", 68, size: 12, x: 45);
        fixture.Line("Example at the previous appointment.", 86, size: 12, x: 45);
        var page = fixture.Page();
        var result = VeteransReviewerNativeEvidencePage.Prepare(page, true);
        var prose = Assert.Single(result.Regions.Where(r => r.Kind == "Narrative"));
        Assert.DoesNotContain(prose.RenderedLines, l => l == "Dr.");
        Assert.Equal(Words(prose.SourceLines), Words(prose.RenderedLines));
        AssertStructuredGeometry(page, result);
        AssertAllInk(page, result);
    }

    [Fact]
    public void RepeatedNativeColumnAnchorsProtectUnlabeledTableGeometry()
    {
        using var fixture = new NativePage(1224, 1584);
        fixture.Line("First clinical description", 50, size: 12, x: 45);
        fixture.Line("result cell one", 50, size: 12, x: 350);
        fixture.Line("Second description", 68, size: 12, x: 45);
        fixture.Line("result cell two", 68, size: 12, x: 350);
        var page = fixture.Page();
        var result = VeteransReviewerNativeEvidencePage.Prepare(page, true);
        Assert.All(result.Regions, r => Assert.Equal("Structured", r.Kind));
        AssertStructuredGeometry(page, result);
        AssertAllInk(page, result);
    }

    [Fact]
    public void Page41_MedicationAndVitalSignRegionsKeepTheirInternalWhitespaceAndXY()
    {
        using var fixture = new NativePage(1224, 1584);
        fixture.Line("22) MEDICATION A  TAKE ONE TABLET DAILY                  ACTIVE", 52, size: 12, x: 45);
        fixture.Line("    Indication: EXAMPLE", 70, size: 12, x: 45);
        fixture.Line("23) MEDICATION B  TAKE AS DIRECTED                       ACTIVE", 88, size: 12, x: 45);
        fixture.Line("OBJECTIVE:", 200, size: 12, x: 45);
        fixture.Line("VITAL SIGNS:", 254, size: 12, x: 45);
        fixture.Line("               6/22/26         6/22/26", 290, size: 12, x: 45);
        fixture.Line("                11:24           11:04", 308, size: 12, x: 45);
        fixture.Line("TEMP           ---             97.9 F (36.6 C)", 326, size: 12, x: 45);
        fixture.Line("PULSE          ---             68", 380, size: 12, x: 45);
        fixture.Line("BP             ---             99/67", 398, size: 12, x: 45);
        var page = fixture.Page();
        var result = VeteransReviewerNativeEvidencePage.Prepare(page, true);
        var vitals = Assert.Single(result.Regions.Where(r => r.SourceLines.Contains("VITAL SIGNS:")));
        Assert.Contains(vitals.SourceLines, l => l.StartsWith("PULSE"));
        Assert.Contains(vitals.SourceLines, l => l.StartsWith("OBJECTIVE"));
        AssertStructuredGeometry(page, result);
        AssertAllInk(page, result);
        Assert.Contains(result.Changes, c => c.Contains("between regions"));
    }

    [Fact]
    public void Page42_PhysicalExamAndLabsKeepNativeResultUnitAndReferenceRelationships()
    {
        using var fixture = new NativePage(1224, 1584);
        fixture.Line("PHYSICAL EXAM:", 70, size: 12, x: 45);
        fixture.Line("General:         No acute distress", 88, size: 12, x: 45);
        fixture.Line("Skin:            Warm, dry.", 106, size: 12, x: 45);
        fixture.Line("Back:            This field includes a deliberately wrapped clinical", 124, size: 12, x: 45);
        fixture.Line("finding", 142, size: 12, x: 45);
        fixture.Line("that must retain its form geometry.", 160, size: 12, x: 45);
        fixture.Line("LABS:", 250, size: 12, x: 45);
        fixture.Line("Collection DT    Specimen   Test Name      Result   Units     Ref", 286, size: 12, x: 45);
        fixture.Line("Range", 304, size: 12, x: 45);
        fixture.Line("01/01/2026       URINE      SQ-EPI         <1       /HPF      0 -", 322, size: 12, x: 45);
        fixture.Line("50", 340, size: 12, x: 45);
        fixture.Line("                 SERUM     GLUCOSE        95       mg/dL     70-99", 394, size: 12, x: 45);
        var page = fixture.Page();
        var result = VeteransReviewerNativeEvidencePage.Prepare(page, true);
        Assert.All(result.Regions, r => Assert.Equal("Structured", r.Kind));
        Assert.Contains(result.Regions, r => r.SourceLines.Contains("Range") && r.SourceLines.Contains("50"));
        AssertStructuredGeometry(page, result);
        AssertAllInk(page, result);
    }

    [Fact]
    public void Pages56To58_RepairAssessmentProseWithoutMovingHeadingsOrNumberedGoalsWithinRegions()
    {
        using var fixture = new NativePage(1224, 1584);
        fixture.Line("RX TODAY:", 70, size: 12, x: 45);
        fixture.Line("1. Evaluation completed", 88, size: 12, x: 45);
        fixture.Line("   -Exercise instructions", 106, size: 12, x: 45);
        fixture.Line("A: The patient was referred for symptoms lasting x", 160, size: 12, x: 45);
        fixture.Line("1", 178, size: 12, x: 45);
        fixture.Line("month. Treatment options reviewed. The patient reports improvement.", 196, size: 12, x: 45);
        fixture.Line("GOALS (3-5 visits):", 250, size: 12, x: 45);
        fixture.Line("1. Continue the first goal", 268, size: 12, x: 45);
        fixture.Line("2. Continue the second goal", 322, size: 12, x: 45);
        var page = fixture.Page();
        var result = VeteransReviewerNativeEvidencePage.Prepare(page, true);
        var prose = Assert.Single(result.Regions.Where(r => r.Kind == "Narrative"));
        Assert.Equal(Words(prose.SourceLines), Words(prose.RenderedLines));
        Assert.DoesNotContain(prose.RenderedLines, l => l == "1");
        AssertStructuredGeometry(page, result);
        AssertAllInk(page, result);
    }

    [Theory]
    [InlineData("SCL2 - GI LABS", "No data available for: IRON", "TIBC", "FERRITIN", "C DIFF TOX B GENE PCR")]
    [InlineData("PENDING TESTS", "Tests pending for review: CBC", "TSH", "B12", "VITAMIN D")]
    public void StackedFieldValuesPreserveSourceLinesAndPixelsWhileNearbyProseStillReflows(
        string heading, string first, string second, string third, string fourth)
    {
        using var fixture = new NativePage(1224, 1584);
        fixture.Line(heading, 52, size: 12, x: 45);
        var fieldLines = new[] { first, second, third, fourth };
        for (var i = 0; i < fieldLines.Length; i++)
            fixture.Line(fieldLines[i], 70 + i * 18, size: 12, x: 45);
        fixture.Line("Attending: We reviewed the findings and discussed care with", 178, size: 12, x: 45);
        fixture.Line("Dr.", 196, size: 12, x: 45);
        fixture.Line("Example before the next appointment.", 214, size: 12, x: 45);
        var page = fixture.Page();
        var result = VeteransReviewerNativeEvidencePage.Prepare(page, true);
        var field = Assert.Single(result.Regions.Where(r => r.SourceLines.Contains(first)));
        Assert.Equal("Structured", field.Kind);
        Assert.Equal(fieldLines, field.SourceLines);
        Assert.Equal(fieldLines, field.RenderedLines);
        AssertStructuredGeometry(page, result);
        AssertAllInk(page, result);
        var prose = Assert.Single(result.Regions.Where(r => r.Kind == "Narrative"));
        Assert.StartsWith("Attending:", prose.SourceLines[0]);
        Assert.True(prose.RenderedLines.Count < prose.SourceLines.Count);
        Assert.DoesNotContain("Dr.", prose.RenderedLines);
        Assert.Equal(Words(prose.SourceLines), Words(prose.RenderedLines));
    }

    private static string[] Words(IEnumerable<string> lines) => lines.SelectMany(l =>
        l.Split(' ', StringSplitOptions.RemoveEmptyEntries)).ToArray();

    private static void AssertAllInk(PrintableArtifactPage page, VeteransReviewerNativeEvidencePage result)
    {
        using var original = SKBitmap.Decode(page.Content.Span);
        using var rendered = SKBitmap.Decode(result.Content.Span);
        Assert.Equal(Ink(original), Ink(rendered));
    }

    private static void AssertStructuredGeometry(PrintableArtifactPage page, VeteransReviewerNativeEvidencePage result)
    {
        using var source = SKBitmap.Decode(page.Content.Span);
        using var target = SKBitmap.Decode(result.Content.Span);
        var original = source.Pixels; var rendered = target.Pixels;
        foreach (var region in result.Regions.Where(r => r.Kind == "Structured"))
        {
            Assert.Equal(region.SourceBottom - region.SourceTop, region.TargetBottom - region.TargetTop);
            Assert.Equal(region.SourceLines, region.RenderedLines);
            for (var y = region.SourceTop; y < region.SourceBottom; y++)
            for (var x = 0; x < source.Width; x++)
            {
                var tx = x + region.HorizontalOffset;
                var ty = y - region.SourceTop + region.TargetTop;
                if (tx >= 0 && tx < target.Width && ty >= 0 && ty < target.Height)
                    Assert.Equal(original[y * source.Width + x], rendered[ty * target.Width + tx]);
                else Assert.Equal(SKColors.White, original[y * source.Width + x]);
            }
        }
    }

    private static KeyValuePair<uint, int>[] Ink(SKBitmap bitmap) => bitmap.Pixels
        .Where(p => p != SKColors.White).GroupBy(p => (uint)p)
        .Select(g => new KeyValuePair<uint, int>(g.Key, g.Count())).OrderBy(p => p.Key).ToArray();

    private sealed class NativePage : IDisposable
    {
        public SKBitmap Bitmap { get; }
        private readonly List<PrintableArtifactGlyph> _glyphs = [];
        public NativePage(int width = 600, int height = 800) { Bitmap = new(width, height); Bitmap.Erase(SKColors.White); }
        public void Line(string text, double baseline, string font = "RobotoMono", double size = 10, double x = 20)
        {
            foreach (var c in text)
            {
                if (c != ' ')
                {
                    var left = x + .5;
                    var right = x + size * .5;
                    var top = baseline - size * .7;
                    var bottom = baseline + size * .1;
                    _glyphs.Add(new(c.ToString(), x, x + size * .6, top, bottom, left, right, baseline, font, size));
                    var color = new SKColor((byte)(_glyphs.Count % 240), (byte)c, 50);
                    for (var yy = (int)Math.Ceiling(top * 2); yy < (int)(bottom * 2); yy++)
                    for (var xx = (int)Math.Ceiling(left * 2); xx < (int)(right * 2); xx++)
                        if (xx < Bitmap.Width) Bitmap.SetPixel(xx, yy, color);
                }
                x += size * .6;
            }
        }
        public PrintableArtifactPage Page(bool graphics = false, bool missingGeometry = false)
        {
            using var image = SKImage.FromBitmap(Bitmap);
            using var png = image.Encode(SKEncodedImageFormat.Png, 100);
            return new() { PageNumber = 440, ContentType = "image/png", Content = png.ToArray(),
                TextGeometry = missingGeometry ? null : new(Bitmap.Width / 2d, Bitmap.Height / 2d, graphics, _glyphs) };
        }
        public void Dispose() => Bitmap.Dispose();
    }
}
