using System.Text;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using EMF.Core.Models;
using EMF.Core.Models.Identities;
using EMF.Extensions.VeteransClaims.Models.Adjudication;
using EMF.Extensions.VeteransClaims.Models.Identities;
using EMF.Extensions.VeteransClaims.Orchestration;

namespace EMF.Tests;

public sealed class VeteransReviewerEvidencePresentationTests
{
    internal const string Header = "Example, Robin Date of birth: May 6, 1970\n" +
        "Report generated by My HealtheVet on VA.gov on August 8, 2026\nPage 17 of 900";
    internal const string ClinicalText = "Encounter: 2025-03-04\n" +
        "Diagnosis: inflammatory arthritis\n" +
        "Test          Result    Units\n" +
        "Temperature   37.2      C\n" +
        "Pulse\t72\t/min\n" +
        "MEDICATIONS:\nDrug A 5 mg daily\nACTIVE\n" +
        "Status: discontinued on 2025-04-01\nNo active infection.\n" +
        "See Page 17 of 900 for the previous measurement.\n" +
        "Date of birth documented in clinical history: 1970-05-06";

    [Theory]
    [InlineData("VA Blue Button Report")]
    [InlineData("VA-Blue-Button-export.pdf")]
    public void Normalize_RemovesVerifiedHeadersButPreservesClinicalContent(string sourceName)
    {
        var input = Header + "\n" + ClinicalText + "\n" + Header;
        var content = Content(input, sourceName);
        var presentation = VeteransReviewerEvidencePresentation.Create(content, []);
        var output = presentation.Normalize(input);

        Assert.DoesNotContain("Example, Robin", output);
        Assert.DoesNotContain("Report generated", output);
        Assert.Contains(ClinicalText, output);
        Assert.Equal(input, content.Text);
        Assert.Equal(output, presentation.Normalize(output));
    }

    internal const string ScrambledHeader =
        "Test          Result    Units\n" +
        "Temperature   37.2      C Report generated by My HealtheVet on VA.gov on September 9, 2026 Pulse: 72\n" +
        "Oxygen: 98%\nDate of birth: April 12, 1956\n" +
        "Dose: 5 mg\nACTIVE\nPage 512 of 4024 Gould, Michael Allen\n" +
        "Follow-up: 2026-10-01";

    [Theory]
    [InlineData(VeteransReviewerPackageAppendix.MedicalEvidence, false)]
    [InlineData(VeteransReviewerPackageAppendix.LayEvidence, false)]
    [InlineData(VeteransReviewerPackageAppendix.LayEvidence, true)]
    public void Render_ScrambledBlueButtonHeaderPreservesAdjacentValues(string appendix, bool printable)
    {
        var content = Content(ScrambledHeader, appendix: appendix,
            pages: printable ? [TextPage(512, ScrambledHeader)] : []);
        var presentation = VeteransReviewerEvidencePresentation.Create(content, [], "Michael Allen Gould");
        var normalized = presentation.Normalize(ScrambledHeader);
        Assert.DoesNotContain("Report generated", normalized);
        Assert.DoesNotContain("Date of birth:", normalized);
        Assert.DoesNotContain("Page 512 of 4024", normalized);
        Assert.DoesNotContain("Gould, Michael Allen", normalized);
        foreach (var value in new[] { "Temperature   37.2      C", "Pulse: 72",
                     "Oxygen: 98%", "Dose: 5 mg", "ACTIVE", "Follow-up: 2026-10-01" })
            Assert.Contains(value, normalized);
        Assert.Equal(normalized, presentation.Normalize(normalized));
        var bytes = VeteransReviewerPackageDocxRenderer.Render(Details([content], veteranDisplayName: "Michael Allen Gould"));
        using var document = WordprocessingDocument.Open(new MemoryStream(bytes), false);
        var text = document.MainDocumentPart!.Document!.Body!.InnerText;
        Assert.DoesNotContain("Report generated", text);
        Assert.DoesNotContain("Gould, Michael Allen", text);
        foreach (var value in new[] { "37.2", "72", "98%", "5 mg", "ACTIVE", "2026-10-01" })
            Assert.Contains(value, text);
        Assert.Equal(ScrambledHeader, content.Text);
    }

    private const string ScrambledGeneration =
        "Report generated by My HealtheVet on VA.gov on September 9, 2026";
    private const string ScrambledDob = "DOB: May 6, 1970";

    public static IEnumerable<object[]> ScrambledExtractionPatterns()
    {
        // Synthetic values, with the producer fragments interleaved exactly as
        // extraction can place them. Expected text is independent of the matcher.
        yield return
        [
            "Test          Result    Units\n" +
            "Glucose   103 " + ScrambledGeneration + "   mg/dL\n" +
            "Creatinine   0.9 Date of birth: May 6, 1970 mg/dL   ACTIVE\n" +
            "Pulse\t72\t/min Page 512 of 4024 Example, Robin \"\n" +
            "Continue 5 mg daily.",
            "Test          Result    Units\n" +
            "Glucose   103    mg/dL\n" +
            "Creatinine   0.9  mg/dL   ACTIVE\n" +
            "Pulse\t72\t/min \nContinue 5 mg daily."
        ];
        yield return
        [
            "I take 5 mg " + ScrambledGeneration + " each morning.\n" +
            "Please " + ScrambledDob + " keep my current dose; symptoms are stable.\n" +
            "Thank you. Page 422 of 4024 Example,\nRobin\n" +
            "Please reply before Friday.",
            "I take 5 mg  each morning.\n" +
            "Please  keep my current dose; symptoms are stable.\n" +
            "Thank you. \nPlease reply before Friday."
        ];
    }

    [Theory]
    [MemberData(nameof(ScrambledExtractionPatterns))]
    public void Normalize_RealScrambledPatternsPreserveEverySurroundingByte(string input, string expected)
    {
        const string before = "Clinical DOB: 1980-01-02; contact Example, Robin.\n";
        const string after = "\nDOB: 1990-03-04\nExample, Robin\n" +
            "See Page 512 of 4024 for prior values.\n" +
            "See Page 422 of 4024 Example, Robin for the quoted message.";
        var content = Content(before + input + after);
        var presentation = VeteransReviewerEvidencePresentation.Create(content, [], "Robin Example");
        var actual = presentation.Normalize(content.Text);
        Assert.Equal(Encoding.UTF8.GetBytes(before + expected + after), Encoding.UTF8.GetBytes(actual));
        Assert.Equal(actual, presentation.Normalize(actual));
        Assert.Equal(before + input + after, content.Text);

        // Text that mentions Blue Button, even with these exact fragments, does
        // not establish source provenance.
        var lay = Content("My Blue Button notes:\n" + input, "Personal statement",
            VeteransReviewerPackageAppendix.LayEvidence);
        Assert.Equal(lay.Text, VeteransReviewerEvidencePresentation.Create(lay, []).Normalize(lay.Text));
    }

    [Theory]
    [MemberData(nameof(ScrambledExtractionPatterns))]
    public void Render_RealScrambledPatternsPreserveMedicalAndLayText(string input, string expected)
    {
        foreach (var appendix in new[] { VeteransReviewerPackageAppendix.MedicalEvidence,
                     VeteransReviewerPackageAppendix.LayEvidence })
        foreach (var printable in new[] { false, true })
        {
            var pages = printable ? new[] { TextPage(1, input) } : [];
            var content = Content(input, appendix: appendix, pages: pages);
            var bytes = VeteransReviewerPackageDocxRenderer.Render(Details([content]));
            using var document = WordprocessingDocument.Open(new MemoryStream(bytes), false);
            var body = document.MainDocumentPart!.Document!.Body!;
            Assert.DoesNotContain("Report generated", body.InnerText);
            Assert.DoesNotContain(ScrambledDob, body.InnerText);
            Assert.DoesNotContain("Date of birth: May 6, 1970", body.InnerText);
            Assert.DoesNotContain("Example, Robin", body.InnerText);
            Assert.DoesNotContain("Page 512 of 4024", body.InnerText);
            Assert.DoesNotContain("Page 422 of 4024", body.InnerText);
            // Tabs are expanded by the renderer, but every word, value and
            // remaining space on each non-tab line must survive verbatim.
            foreach (var line in expected.Split('\n').Where(line => !line.Contains('\t')))
                Assert.Contains(body.Descendants<Paragraph>(), paragraph => paragraph.InnerText == line);
            Assert.Equal(input, content.Text);
            if (printable)
                Assert.Equal(Encoding.UTF8.GetBytes(input), pages[0].Content.ToArray());
        }
    }

    [Theory]
    [InlineData("\n", "")]
    [InlineData("\r\n", "")]
    [InlineData("\r", "")]
    [InlineData("\n", " \"")]
    public void Normalize_SplitMiddleNameRemovesWholeIdentityAndPreservesFollowingNarrative(
        string separator, string punctuation)
    {
        var input = "I take 5 mg " + ScrambledGeneration + " each morning.\n" +
            "Please " + ScrambledDob + " keep the dose unchanged.\n" +
            "Thank you. Page 422 of 4024 Example, Robin" + separator + "Allen" + punctuation + "\n" +
            "Please continue treatment.\nACTIVE symptoms require follow-up.";
        const string expected = "I take 5 mg  each morning.\n" +
            "Please  keep the dose unchanged.\n" +
            "Thank you. \nPlease continue treatment.\nACTIVE symptoms require follow-up.";
        var content = Content(input, appendix: VeteransReviewerPackageAppendix.LayEvidence);
        var presentation = VeteransReviewerEvidencePresentation.Create(content, [], "Robin Allen Example");
        var actual = presentation.Normalize(input);

        Assert.Equal(Encoding.UTF8.GetBytes(expected), Encoding.UTF8.GetBytes(actual));
        Assert.DoesNotContain("Allen", actual);
        Assert.DoesNotContain("Example", actual);
        Assert.DoesNotContain("Robin", actual);
        Assert.Equal(actual, presentation.Normalize(actual));
        Assert.Equal(input, content.Text);

        const string verifiedHeader = "Example, Robin Allen Date of birth: May 6, 1970\n" +
            ScrambledGeneration + "\nPage 1 of 4024";
        foreach (var printable in new[] { false, true })
        {
            var renderedContent = Content(verifiedHeader + "\n" + input, appendix: VeteransReviewerPackageAppendix.LayEvidence,
                pages: printable ? [TextPage(422, input)] : []);
            var bytes = VeteransReviewerPackageDocxRenderer.Render(Details([renderedContent]));
            using var document = WordprocessingDocument.Open(new MemoryStream(bytes), false);
            var body = document.MainDocumentPart!.Document!.Body!;
            Assert.DoesNotContain("Allen", body.InnerText);
            foreach (var line in expected.Split('\n'))
                Assert.Contains(body.Descendants<Paragraph>(), paragraph => paragraph.InnerText == line);
        }
    }

    [Theory]
    [InlineData("ACTIVE")]
    [InlineData("COMPLETED")]
    [InlineData("SIGNED")]
    [InlineData("Reviewed")]
    [InlineData("Observation")]
    [InlineData("Allen")]
    [InlineData("ACTIVE\nCOMPLETED\nSIGNED\nAnyOtherClinicalText")]
    public void Normalize_GroundedIdentityPreservesAllFollowingLines(string followingText)
    {
        foreach (var (identity, displayName) in new[]
        {
            ("Example, Robin", "Robin Example"),
            ("Example,\nRobin", "Robin Example"),
            ("Example, Robin\nAllen", "Robin Allen Example")
        })
        foreach (var useVerifiedHeader in new[] { false, true })
        {
            var input = ScrambledMessageWithIdentity(identity, followingText);
            var expected = ScrambledMessageWithoutIdentity(followingText);
            var verifiedHeader = identity.Replace('\n', ' ') +
                " Date of birth: May 6, 1970\n" + ScrambledGeneration + "\nPage 1 of 4024";
            // A shorter display name must not truncate a name verified by the
            // source, and no status-word vocabulary is needed to stop the match.
            var presentation = VeteransReviewerEvidencePresentation.Create(
                Content(input), useVerifiedHeader ? [verifiedHeader] : [],
                useVerifiedHeader ? "Robin Example" : displayName);
            var actual = presentation.Normalize(input);

            Assert.Equal(Encoding.UTF8.GetBytes(expected), Encoding.UTF8.GetBytes(actual));
            Assert.Equal(actual, presentation.Normalize(actual));
        }
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public void Render_GroundedIdentityPreservesFollowingStatusAndNarrativeLines(bool useVerifiedHeader)
    {
        const string followingText = "ACTIVE\nCOMPLETED\nSIGNED\nReviewed\nAnyOtherClinicalText";
        var input = ScrambledMessageWithIdentity("Example, Robin\nAllen", followingText);
        var expected = ScrambledMessageWithoutIdentity(followingText);
        var verifiedHeader = "Example, Robin Allen Date of birth: May 6, 1970\n" +
            ScrambledGeneration + "\nPage 1 of 4024";
        foreach (var printable in new[] { false, true })
        {
            var content = Content(
                useVerifiedHeader ? verifiedHeader + "\n" + input : input,
                appendix: VeteransReviewerPackageAppendix.LayEvidence,
                pages: printable ? [TextPage(422, input)] : []);
            var bytes = VeteransReviewerPackageDocxRenderer.Render(Details([content],
                veteranDisplayName: useVerifiedHeader ? "Robin Example" : "Robin Allen Example"));
            using var document = WordprocessingDocument.Open(new MemoryStream(bytes), false);
            var paragraphs = document.MainDocumentPart!.Document!.Body!.Descendants<Paragraph>()
                .Select(paragraph => paragraph.InnerText).ToArray();
            var start = Array.IndexOf(paragraphs, "Message  continues.");
            Assert.True(start >= 0);
            Assert.Equal(expected.Split('\n'), paragraphs.Skip(start).Take(expected.Split('\n').Length));
            Assert.DoesNotContain("Allen", string.Join("\n", paragraphs.Skip(start)));
        }
    }

    [Theory]
    [InlineData(null)]
    [InlineData("Other Patient")]
    public void Normalize_UnknownIdentityIsNotInferredFromCapitalizedLines(string? displayName)
    {
        var input = ScrambledMessageWithIdentity("Example, Robin\nAllen", "COMPLETED\nNarrative");
        var presentation = VeteransReviewerEvidencePresentation.Create(Content(input), [], displayName);
        Assert.Equal(input, presentation.Normalize(input));
    }

    [Fact]
    public void Normalize_KnownNameDoesNotAuthorizeCleanupOfOrdinaryLayText()
    {
        var input = ScrambledMessageWithIdentity("Example, Robin\nAllen", "COMPLETED");
        var content = Content(input, "Personal statement", VeteransReviewerPackageAppendix.LayEvidence);
        var presentation = VeteransReviewerEvidencePresentation.Create(content, [], "Robin Allen Example");
        Assert.Equal(input, presentation.Normalize(input));
    }

    private static string ScrambledMessageWithIdentity(string identity, string followingText) =>
        "Message " + ScrambledGeneration + " continues.\n" +
        "Please " + ScrambledDob + " retain the 5 mg dose.\n" +
        "Thank you. Page 422 of 4024 " + identity + "\n" + followingText;

    private static string ScrambledMessageWithoutIdentity(string followingText) =>
        "Message  continues.\nPlease  retain the 5 mg dose.\nThank you. \n" + followingText;

    [Theory]
    [InlineData("generation")]
    [InlineData("dob")]
    [InlineData("identity")]
    [InlineData("ambiguous-dob")]
    [InlineData("identity-with-prose")]
    public void Normalize_IncompleteOrAmbiguousScrambledClusterIsUnchanged(string variant)
    {
        var input = "Message " + ScrambledGeneration + " continues.\n" +
            ScrambledDob + " mg/dL\nPage 422 of 4024 Example,\nRobin \"\nEnd.";
        input = variant switch
        {
            "generation" => input.Replace(ScrambledGeneration, "Report mentioned in narrative"),
            "dob" => input.Replace(ScrambledDob, "Clinical history"),
            "identity" => input.Replace("Example,\nRobin \"", "for the previous measurement."),
            "identity-with-prose" => input.Replace("Example,\nRobin \"", "Example, Robin reports stable symptoms."),
            _ => input.Replace(ScrambledDob, ScrambledDob + " other DOB: 1980-01-02")
        };
        var presentation = VeteransReviewerEvidencePresentation.Create(Content(input), [], "Robin Example");
        Assert.Equal(input, presentation.Normalize(input));
    }

    [Theory]
    [InlineData("Symptoms are stable.  Follow up next month.")]
    [InlineData("  Ordinary indented prose.")]
    [InlineData("Stable symptoms.  Continue care.  Return next month.")]
    public void Render_DoubleSpacedProseUsesNarrativeFont(string prose)
    {
        var bytes = VeteransReviewerPackageDocxRenderer.Render(Details([Content(prose)]));
        using var document = WordprocessingDocument.Open(new MemoryStream(bytes), false);
        var paragraph = Assert.Single(document.MainDocumentPart!.Document!.Body!
            .Descendants<Paragraph>().Where(p => p.InnerText == prose));
        Assert.Equal("Cambria", paragraph.Descendants<RunFonts>().Single().Ascii!.Value);
    }

    [Fact]
    public void Normalize_InlineHeaderDoesNotConsumeSurroundingMedicalText()
    {
        var input = "Before: 12 mg. " + Header.Replace('\n', ' ') + " After: 18 mg.";
        var normalizer = VeteransReviewerEvidencePresentation.Create(Content(input), []);
        var output = normalizer.Normalize(input);
        Assert.Contains("Before: 12 mg.", output);
        Assert.Contains("After: 18 mg.", output);
        Assert.DoesNotContain("Report generated", output);
    }

    [Fact]
    public void Normalize_RepeatedIdentityRequiresACompleteVerifiedHeader()
    {
        const string identity = "Example, Robin Date of birth: May 6, 1970";
        var normalizer = VeteransReviewerEvidencePresentation.Create(Content(Header), [Header]);
        Assert.DoesNotContain(identity, normalizer.Normalize(identity + "\n" + ClinicalText));
        var splitIdentity = identity.Replace(" Date of birth:", "\r\nDate of birth:");
        Assert.DoesNotContain("Example, Robin", normalizer.Normalize(splitIdentity + "\r\n" + ClinicalText));
        Assert.Contains(ClinicalText, normalizer.Normalize(splitIdentity + "\r\n" + ClinicalText));
        const string ambiguous = "Other, Patient DOB: 1972-01-01\nDOB: 1970-05-06\nACTIVE\nStatus\nDiagnosis: ACTIVE disease";
        Assert.Equal(ambiguous, normalizer.Normalize(ambiguous));
        var unknown = VeteransReviewerEvidencePresentation.Create(Content(identity), []);
        Assert.Equal(identity, unknown.Normalize(identity));
    }

    [Theory]
    [InlineData(null, "ordinary.pdf", VeteransReviewerPackageAppendix.MedicalEvidence)]
    [InlineData(null, "ordinary.docx", VeteransReviewerPackageAppendix.MedicalEvidence)]
    [InlineData("Personal statement", "letter.docx", VeteransReviewerPackageAppendix.LayEvidence)]
    [InlineData("Research study", "study.pdf", VeteransReviewerPackageAppendix.MedicalLiterature)]
    public void Normalize_DoesNotApplySourceRulesToOtherEvidence(string? source, string name, string appendix)
    {
        var text = Header + "\n" + ClinicalText;
        var content = Content(text, source, appendix, name);
        var presentation = VeteransReviewerEvidencePresentation.Create(content, []);
        Assert.False(presentation.IsBlueButton);
        Assert.Equal(text, presentation.Normalize(text));
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public async Task Render_BlueButtonTextAndMultiplePagesShareCanonicalOutput(bool printablePages)
    {
        var original = Header + "\n" + ClinicalText;
        var pages = printablePages
            ? new[] { TextPage(1, original), TextPage(2, Header + "\nFollow-up: 2025-05-02\nMeasurement: 15 mm") }
            : [];
        var content = Content(original, pages: pages);
        var converter = new RecordingConverter();
        var output = await new VeteransReviewerPackageDocumentOutputService(converter)
            .RenderAsync(Details([content]), VeteransReviewerPackageOutputFormat.Both);
        Assert.Equal(output.Docx, converter.Docx);
        using var document = WordprocessingDocument.Open(new MemoryStream(output.Docx!), false);
        var body = document.MainDocumentPart!.Document!.Body!;
        Assert.Contains("Veteran: Robin Example", body.InnerText);
        Assert.DoesNotContain("Report generated", body.InnerText);
        Assert.DoesNotContain("Date of birth: May 6, 1970", body.InnerText);
        Assert.Contains("Diagnosis:inflammatory arthritis", body.InnerText);
        Assert.Contains("Status:discontinued on 2025-04-01", body.InnerText);
        Assert.Contains("Drug A 5 mg daily", body.InnerText);
        Assert.Contains("No active infection.", body.InnerText);
        Assert.Contains(body.Descendants<Paragraph>(), p => p.InnerText == "ACTIVE");
        var row = Assert.Single(body.Descendants<Paragraph>().Where(p => p.InnerText == "Temperature   37.2      C"));
        Assert.Equal("Consolas", row.Descendants<RunFonts>().Single().Ascii!.Value);
        Assert.Contains(body.Descendants<Paragraph>(), p => p.InnerText == "Pulse   72      /min");
        Assert.Contains("See Page 17 of 900 for the previous measurement.", body.InnerText);
        if (printablePages)
        {
            Assert.Contains("Source Page 1", body.InnerText);
            Assert.Contains("Source Page 2", body.InnerText);
            Assert.Contains("2025-05-02", body.InnerText);
            Assert.Contains("15 mm", body.InnerText);
            Assert.Equal(original, Encoding.UTF8.GetString(pages[0].Content.Span));
        }
        Assert.Equal(original, content.Text);
    }

    [Theory]
    [InlineData("ordinary.pdf", VeteransReviewerPackageAppendix.MedicalEvidence)]
    [InlineData("ordinary.docx", VeteransReviewerPackageAppendix.MedicalEvidence)]
    [InlineData("lay.docx", VeteransReviewerPackageAppendix.LayEvidence)]
    [InlineData("article.pdf", VeteransReviewerPackageAppendix.MedicalLiterature)]
    [InlineData("VA-Blue-Button-original.pdf", VeteransReviewerPackageAppendix.MedicalEvidence)]
    public void Render_PrintablePdfAndDocxImagesRemainAuthoritative(string name, string appendix)
    {
        var png = Convert.FromBase64String("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=");
        var content = Content("Extracted text must not replace the preserved page.", null, appendix, name,
            [new PrintableArtifactPage { PageNumber = 1, ContentType = "image/png", Content = png }]);
        var bytes = VeteransReviewerPackageDocxRenderer.Render(Details([content]));
        using var document = WordprocessingDocument.Open(new MemoryStream(bytes), false);
        using var image = Assert.Single(document.MainDocumentPart!.ImageParts).GetStream();
        using var copy = new MemoryStream();
        image.CopyTo(copy);
        Assert.Equal(png, copy.ToArray());
        Assert.Single(document.MainDocumentPart.Document!.Body!.Descendants<Drawing>());
        if (appendix != VeteransReviewerPackageAppendix.MedicalLiterature)
            Assert.DoesNotContain(content.Text, document.MainDocumentPart.Document.Body!.InnerText);
    }

    [Theory]
    [InlineData(VeteransReviewerPackageAppendix.LayEvidence)]
    [InlineData(VeteransReviewerPackageAppendix.MedicalLiterature)]
    public void Render_NonClinicalTextRetainsQuotedBlueButtonHeader(string appendix)
    {
        var content = Content("I reviewed Blue Button.\n" + Header + "\n" + ClinicalText, "Personal statement", appendix);
        var bytes = VeteransReviewerPackageDocxRenderer.Render(Details([content]));
        using var document = WordprocessingDocument.Open(new MemoryStream(bytes), false);
        var text = document.MainDocumentPart!.Document!.Body!.InnerText;
        Assert.Contains("Report generated by My HealtheVet", text);
        Assert.Contains("Page 17 of 900", text);
        Assert.Contains("inflammatory arthritis", text);
    }

    [Fact]
    public void Render_BlueButtonInvalidUtf8StillFailsClosed()
    {
        var content = Content(Header, pages: [new PrintableArtifactPage
        { PageNumber = 1, ContentType = "text/plain", Content = new byte[] { 0xff } }]);
        Assert.Throws<InvalidDataException>(() => VeteransReviewerPackageDocxRenderer.Render(Details([content])));
    }

    internal static VeteransReviewerArtifactContent Content(string text,
        string? source = "VA Blue Button Report",
        string appendix = VeteransReviewerPackageAppendix.MedicalEvidence,
        string name = "source-note", IReadOnlyList<PrintableArtifactPage>? pages = null) => new()
    {
        Artifact = new Artifact { Id = new ArtifactId(name), Name = name, ArtifactType = "medical-record" },
        Text = text, SourceName = source, Appendix = appendix, PrintablePages = pages ?? []
    };

    internal static VeteransReviewerPackageDetails Details(
        IReadOnlyList<VeteransReviewerArtifactContent> contents,
        ServiceConnectionBasisId? basis = null,
        string? veteranDisplayName = "Robin Example") => new()
    {
        PackageDetails = new EvidencePackageDetails
        {
            Package = new EvidencePackage
            {
                Id = new EvidencePackageId("presentation-package"), ClaimIssueId = new ClaimIssueId("issue-1"),
                Purpose = "Physician review", ReviewerRole = "MedicalProfessional", ServiceConnectionBasisId = basis
            },
            Artifacts = contents.Select(c => new EvidencePackageArtifact
            {
                EvidencePackageId = new EvidencePackageId("presentation-package"), ArtifactId = c.Artifact.Id,
                ContentRole = EvidencePackageContentRoles.UnderlyingEvidence
            }).ToArray()
        },
        Artifacts = contents.Select(c => c.Artifact).ToArray(), ArtifactContents = contents,
        VeteranDisplayName = veteranDisplayName
    };

    private static PrintableArtifactPage TextPage(int number, string text) => new()
    { PageNumber = number, ContentType = "text/plain", Content = Encoding.UTF8.GetBytes(text) };

    private sealed class RecordingConverter : IVeteransReviewerPackageDocumentConverter
    {
        public byte[]? Docx { get; private set; }
        public Task<byte[]> ConvertDocxToPdfAsync(ReadOnlyMemory<byte> docx, CancellationToken cancellationToken = default)
        {
            Docx = docx.ToArray();
            return Task.FromResult(Encoding.ASCII.GetBytes("%PDF-1.7\n"));
        }
    }
}
