<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EMF.Extensions.VeteransClaims\EMF.Extensions.VeteransClaims.csproj" />
    <ProjectReference Include="..\EMF.Extensions.VeteransClaims.Persistence.Sqlite\EMF.Extensions.VeteransClaims.Persistence.Sqlite.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
